# Generated by Django 4.0.5 on 2023-05-21 23:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_order_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='transactionID',
            field=models.CharField(blank=True, default='', max_length=12),
        ),
    ]
