# Generated by Django 4.0.5 on 2023-05-23 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_order_transactionid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='transactionID',
            field=models.CharField(default='DEFAULT_VALUE', max_length=13, null=True),
        ),
    ]
